config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :docs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
	before_action :ficd_doc, only: [:show, :edit, :update, :destroy]

	def index
		@docs = Doc.all.order("created_at DESC")
	end

	def show
	end
	def new
        @doc =Doc.new(doc_params)
     if @doc.save
        redirect_to @doc
    else
        render 'new'
      end
    end

	def create
	end

	def edit
		
	end

	def update
       if @doc.update(doc_params)
          redirect_to @doc
    else
          render 'edit'
      end
    end

    def destroy
		 @doc.destroy
		 redirect_to docs_path
    end

	private
	
	def find_doc
    @doc = Doc.find(params[:id])
    end

	def doc_params
    params.require(:doc).permit(:title, :content)
    end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/edit.html.haml
%h1 Fix Doc!
= render 'form'
= link_to "Cancel" , doc_path

app/views/docs/index.html.haml
-@docs.each do |doc|
	%h2= link_to doc.title, doc
	%p= time_ago_in_words(doc.created_at)
	%p= truncate(doc.content, length:50)

app/views/docs/new.html.haml
new.html.haml >> %h1 New Doc!
= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%h1= @doc.content

= link_to "All Docs", docs_path  
= link_to "Fix Doc", edit_doc_path9@doc)
= link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm:"R U SURE!"}
= link_to "Create Doc", new_dodc_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabient</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
%h1 voila! This is the Placeholder!!